---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/masks":
    get:
      summary: 取得所有口罩 (支援搜尋與篩選)
      tags:
      - Masks
      parameters:
      - name: keyword
        in: query
        description: 口罩名稱關鍵字
        schema:
          type: string
      - name: stock_gt
        in: query
        description: 庫存大於
        schema:
          type: integer
      - name: stock_lt
        in: query
        description: 庫存小於
        schema:
          type: integer
      - name: price_min
        in: query
        description: 價格大於等於
        schema:
          type: number
      - name: price_max
        in: query
        description: 價格小於等於
        schema:
          type: number
      - name: sort
        in: query
        description: 排序方式(price_asc、price_desc、name_asc、name_desc)
        schema:
          type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        price:
                          type: number
                        stock:
                          type: integer
                        pharmacy:
                          type: object
                          properties:
                            id:
                              type: integer
                            name:
                              type: string
  "/api/orders/analytics/top_users":
    get:
      summary: Top Users 排行榜
      tags:
      - Orders Analytics
      parameters:
      - name: start_date
        in: query
        required: true
        description: 起始日期 yyyy-mm-dd
        schema:
          type: string
      - name: end_date
        in: query
        required: true
        description: 結束日期 yyyy-mm-dd
        schema:
          type: string
      - name: limit
        in: query
        required: false
        description: 前幾名（預設5）
        schema:
          type: integer
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            user_id:
                              type: integer
                            user_name:
                              type: string
                            total_amount:
                              type: number
                            total_quantity:
                              type: integer
                            orders:
                              type: array
                              items:
                                type: object
                                properties:
                                  pharmacy_name:
                                    type: string
                                  total_price:
                                    type: number
                                  created_at:
                                    type: string
                                    format: date_time
                                  items:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        mask_id:
                                          type: integer
                                        mask_name:
                                          type: string
                                        price:
                                          type: number
                                        quantity:
                                          type: integer
  "/api/orders/analytics/statistics":
    get:
      summary: 訂單統計
      tags:
      - Orders Analytics
      parameters:
      - name: start_date
        in: query
        required: true
        description: 起始日期 yyyy-mm-dd
        schema:
          type: string
      - name: end_date
        in: query
        required: true
        description: 結束日期 yyyy-mm-dd
        schema:
          type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      total_quantity:
                        type: integer
                      total_amount:
                        type: number
                      mask_summary:
                        type: array
                        items:
                          type: object
                          properties:
                            mask_id:
                              type: integer
                            mask_name:
                              type: string
                            total_quantity:
                              type: integer
                            total_amount:
                              type: number
                      pharmacy_summary:
                        type: array
                        items:
                          type: object
                          properties:
                            pharmacy_id:
                              type: integer
                            pharmacy_name:
                              type: string
                            total_quantity:
                              type: integer
                            total_amount:
                              type: number
  "/api/orders":
    get:
      summary: 取得所有訂單
      tags:
      - Orders
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            user_name:
                              type: string
                            pharmacy_name:
                              type: string
                            total_price:
                              type: number
                            created_at:
                              type: string
                              format: date_time
                            items:
                              type: array
                              items:
                                type: object
                                properties:
                                  mask_name:
                                    type: string
                                  price:
                                    type: number
                                  quantity:
                                    type: integer
    post:
      summary: 建立訂單
      tags:
      - Orders
      parameters: []
      responses:
        '200':
          description: 建立成功
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                mask_id:
                  type: integer
                quantity:
                  type: integer
              required:
              - user_id
              - mask_id
              - quantity
  "/api/orders/{id}":
    get:
      summary: 取得指定訂單
      tags:
      - Orders
      parameters:
      - name: id
        in: path
        required: true
        description: Order ID
        schema:
          type: integer
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      user_name:
                        type: string
                      pharmacy_name:
                        type: string
                      total_price:
                        type: number
                      created_at:
                        type: string
                        format: date_time
                      items:
                        type: array
                        items:
                          type: object
                          properties:
                            mask_name:
                              type: string
                            price:
                              type: number
                            quantity:
                              type: integer
  "/api/pharmacies":
    get:
      summary: 取得所有藥局（支援 keyword / day_of_week / time 篩選）
      tags:
      - Pharmacies
      parameters:
      - name: keyword
        in: query
        required: false
        description: 模糊搜尋藥局名稱
        schema:
          type: string
      - name: day_of_week
        in: query
        required: false
        description: 篩選營業日（0=週日）
        schema:
          type: integer
      - name: time
        in: query
        required: false
        description: 篩選時間（HH:mm）
        schema:
          type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        opening_hours_text:
                          type: string
  "/api/pharmacies/{id}":
    get:
      summary: 取得藥局詳細資料
      tags:
      - Pharmacies
      parameters:
      - name: id
        in: path
        description: Pharmacy ID
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      cash_balance:
                        type: number
                      opening_hours_text:
                        type: string
        '404':
          description: 找不到資料
  "/api/pharmacies/{pharmacy_id}/masks":
    get:
      summary: 取得某藥局的所有口罩
      tags:
      - Pharmacies
      parameters:
      - name: pharmacy_id
        in: path
        required: true
        description: Pharmacy ID
        schema:
          type: integer
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        price:
                          type: string
                        stock:
                          type: integer
                        pharmacy_id:
                          type: integer
                        created_at:
                          type: string
                          format: date_time
                        updated_at:
                          type: string
                          format: date_time
  "/api/users/{id}":
    get:
      summary: 取得單一使用者
      tags:
      - Users
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      cash_balance:
                        type: number
servers:
- url: http://35.229.247.36:3000
